# Generated by Django 6.0.6 on 2026-06-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('Bike', 'Bike'), ('Car', 'Car')], max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('parking_slot', models.CharField(max_length=10)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('Parked', 'Parked'), ('Exited', 'Exited')], default='Parked', max_length=10)),
            ],
        ),
    ]
