# Generated by Django 5.2.8 on 2026-07-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_vehicle_qr_code_alter_vehicle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
    ]
