# Generated by Django 5.2.8 on 2026-07-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_alter_vehicle_amount_alter_vehicle_entry_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
