# Generated by Django 5.2.8 on 2026-07-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_vehicle_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_name', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('one_day_fee', models.PositiveIntegerField(default=20)),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='default_language',
            field=models.CharField(choices=[('en', 'English'), ('ta', 'Tamil')], default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='parking_logo',
            field=models.ImageField(blank=True, null=True, upload_to='parking_logo/'),
        ),
    ]
