# Generated by Django 5.2.8 on 2026-07-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_parkingsetup_vehicle_default_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='default_language',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='parking_logo',
        ),
        migrations.AddField(
            model_name='parkingsetup',
            name='default_language',
            field=models.CharField(choices=[('en', 'English'), ('ta', 'Tamil')], default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='parkingsetup',
            name='parking_logo',
            field=models.ImageField(blank=True, null=True, upload_to='parking_logo/'),
        ),
    ]
