# Generated by Django 5.2.8 on 2026-07-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_remove_vehicle_default_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_number',
            field=models.CharField(max_length=20),
        ),
    ]
